Repository jgomezselles/hermes, pull requests merged in 2022-01, with the labels that each got.

#63 Fix Content-Type & Content-Length header keys
  src/http2_client/client_utils.hpp
  ut/http2_client/client_utils_test.cpp
Labels: bug

#64 Fix header post processing
  src/script/script.cpp
  ut/script/script_test.cpp
Labels: bug

#65 Compile only hermes exec in release Dockerfile
  docker/Dockerfile
Labels: CI

#66 Add helm lint to CI workflow
  .github/workflows/ci.yml
Labels: CI, Testing
